---
- name: Deploy - NE Post
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/43/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - NE Post
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - EDS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/12/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - EDS
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - CMS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/5/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - CMS
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DES
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/6/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - DES
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DSS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/10/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - DSS
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DVS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/11/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - DVS
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Change Property - Logstash - istio.sidecar.enabled
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/44/configs/27/profiles/27/contents/istio.sidecar.enabled"
    method: PUT
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
    body:
      configValue: "false"

- name: Deploy - Logstash
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/44/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response
  ignore_errors: yes

- name: Result Deploy - Logstash
  debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"
