---
- hosts: ne-bootstrap
  gather_facts: False
  roles:
    - { role: "ne-storageclass" }
    - { role: "ne-preinstall" }
    - { role: "kube-apiserver" }
    - { role: "ne-login" }
    - { role: "ne-update-kubeapps" }
    - { role: "ne-install-managed" }
    - { role: "ne-install-service" }
