---
- name: Gather facts
  tags: always
  import_playbook: facts.yml

- hosts: ne-bootstrap
  gather_facts: False
  roles:
    - { role: "set-helm-repo" }
    - { role: "ne-ldap"}
    - { role: "ne-storageclass" }
    - { role: "ne-initialize" }
    - { role: "ne-preinstall" }
    - { role: "set-kube-apiserver" }
    - { role: "ne-login" }
    - { role: "ne-update-kubeapps" }
    - { role: "ne-install-managed" }
    - { role: "ne-install-service" }
    - { role: "ne-finalize" }

- hosts: bootstrap
  gather_facts: False
  roles:
    - { role: "ne-etcd"}
