---
- hosts: ne-bootstrap
  gather_facts: False
  roles:
    - { role: "ne-infra" }
    - { role: "set-helm-repo" }
    - { role: "ne-ldap"}
    - { role: "ne-storageclass" }
    - { role: "ne-initialize" }
    - { role: "ne-preinstall" }
    - { role: "set-kube-apiserver" }
    - { role: "ne-login" }
    - { role: "ne-update-kubeapps" }
    - { role: "ne-install-managed" }
    - { role: "ne-install-service" }
    - { role: "ne-finalize" }
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
