---
- hosts: ne-bootstrap
  gather_facts: False
  tasks:
    - include_role:
        name: ne-initialize
        tasks_from: reset
    - include_role:
        name: ne-storageclass
        tasks_from: reset
    - include_role:
        name: set-helm-repo
        tasks_from: reset
