---

- hosts: bootstrap
  gather_facts: False
  tasks:
    - include_role:
        name: ne-etcd
        tasks_from: reset

- hosts: ne-bootstrap
  gather_facts: False
  tasks:
    - include_role:
        name: ne-ldap
        tasks_from: reset
    - include_role:
        name: ne-preinstall
        tasks_from: reset
    - include_role:
        name: ne-initialize
        tasks_from: reset
    - include_role:
        name: ne-storageclass
        tasks_from: reset
    - include_role:
        name: set-helm-repo
        tasks_from: reset
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
