---
- hosts: ne-bootstrap
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:

    - name: Stop Selenium-Chrome
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: selenium-chrome
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60


    - name: Stop Selenium-Hub
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: selenium-hub
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60


    - name: Stop Logstash
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: logstash
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60
      

    - name: Stop DVS
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: dvs
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop DSS
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: dss
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop DES
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: des
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop CMS
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: cms
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop EDS
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: eds
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Conductor-UI
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: conductor-ui
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Conductor-Server
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: conductor-server
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Spark-thriftserver
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: spark-thriftserver
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Spark-historyserver
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: spark-historyserver
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Hive-metastore
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: hive-metastore
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60


    - name: Stop Elasticsearch-Client
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: elasticsearch-client
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Elasticsearch-Ingest
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: elasticsearch-ingest
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Elasticsearch-Master
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: elasticsearch-master
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Elasticsearch-Data
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: elasticsearch-data
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Kafka
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: kafka
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop Zookeeper
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: zookeeper
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop A3S
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: a3s
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop ranger-usersync
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: ranger-usersync
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop ranger-admin
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: ranger-admin
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop openldap
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: openldap
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop CGW
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: cgw
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop CUI
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: cui
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop CCS
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: ccs
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pinpoint-collector
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: pinpoint-collector
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pinpoint-web
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: pinpoint-web
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pinpoint-hbase
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: pinpoint-hbase
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pmm-server
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: pmm-server
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pxc-operator
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: Deployment
        name: pxc-operator
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 60

    - name: Stop pxc-database-proxysql
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: pxc-database-proxysql
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 90

    - name: Sleep for 90 seconds for Checkiing All Pods Running Status
      wait_for:
        timeout: 90

    - name: Stop pxc-database-pxc
      community.kubernetes.k8s_scale:
        api_version: v1
        kind: StatefulSet
        name: pxc-database-pxc
        namespace: "{{ datalake_name }}"
        replicas: 0
        wait_timeout: 90


    - name: Sleep for 90 seconds for Checkiing All Pods Running Status
      wait_for:
        timeout: 90

    - name: Checkiing All Pods Running Status
      community.kubernetes.k8s_info:
        kind: Pod
        namespace: nexr
        field_selectors:
          - status.phase=Running
      register: runningpodstatus
      failed_when:   (runningpodstatus.resources | length) > 0
        