---
- name: Create variable - k8s apiserver url
  shell: "{{ bin_dir }}/kubectl config view --minify | grep server | cut -f 2- -d ':' | tr -d ' '"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  register: apiserver_url

- name: Set variable - k8s apiserver url
  set_fact:
    cacheable: yes
    k8s_api_server: "{{ apiserver_url.stdout }}"

- name: Create variable - k8s secret name
  shell: "{{ bin_dir }}/kubectl get secrets -n {{ k8s_namespace }} | grep ^default | cut -f1 -d ' '"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  register: secret_name

- name: Set variable - k8s secret name
  set_fact:
    cacheable: yes
    k8s_secret_name: "{{ secret_name.stdout }}"

- name: Create variable - k8s api proxy token
  shell: "{{ bin_dir }}/kubectl describe secret {{ k8s_secret_name }} -n {{ k8s_namespace }} | grep -E '^token' | cut -f2 -d':' | tr -d ' '"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  register: api_token

- name: Set variable - k8s api proxy token
  set_fact:
    cacheable: yes
    k8s_api_token: "{{ api_token.stdout }}"

- name: Regist NexR Enterprise license
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/licenses/constantine"
    method: POST
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
    body:
      licenseKey: "{{ ne.licensekey }}"
      siteName: "{{ ne.sitename }}"

- name: Login NexR Enterprise
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/a3s:8189/proxy/auth/login"
    method: POST
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
    body:
      userId: "{{ ne_admin_username }}"
      userPassword: "{{ ne_admin_password }}"
  register: login_response

- debug:
    var: login_response

- name: Set variable - NexR Enterprise accesstoken
  set_fact:
    cacheable: yes
    ne_accesstoken: "{{ login_response.json.body.accessToken }}"
    ne_refreshtoken: "{{ login_response.json.body.refreshToken }}"

- name: Create variable - k8s kubeapps token
  shell: "{{ bin_dir }}/kubectl describe secret $(kubectl get secrets -n default | grep ^kubeapps-operator | cut -f1 -d ' ') -n default | grep -E '^token' | cut -f2 -d':' | tr -d ' '"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  register: kubeapps_token

- name: Set variable - k8s kubeapps token
  set_fact:
    cacheable: yes
    kubeapps_token: "{{ kubeapps_token.stdout }}"

- name: Change Kubeapps rest api info
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/orchestrators/1"
    method: PUT
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
    body:
      endpoint: "http://kubeapps.kubeapps.svc.{{ k8s_cluster_name }}:80"
      namespace: "{{ k8s_namespace }}"
      title: "Kubernetes"
      token: "{{ kubeapps_token }}"
  register: orchestrator_response

- debug:
    var: orchestrator_response

- name: Deploy - Elasticsearch
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/25/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Hive-metastore
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/26/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Spark-historyserver
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/29/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Spark-thriftserver
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/30/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Conductor
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/33/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Selenium
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/41/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Zookeeper
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/35/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Kafka
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/24/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - NE Post
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/43/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - EDS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/12/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - CMS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/5/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DES
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/6/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DSS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/10/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - DVS
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/11/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"

- name: Deploy - Logstash
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/applications/44/deploy"
    method: POST
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
  register: response

- debug:
    var: response
  failed_when:
    - "{{ 'json' not in response }}"
    - "'ERROR' in '{{ response.json.status }}'"
    - "609000 != {{ response.json.errorCode }}"
