# kubectl path
bin_dir: /usr/local/bin

chart_repo_url: http://192.168.70.13:28080/ne-1.3.0
chart_repo_name: ne

k8s_namespace: ne
k8s_cluster_name: cluster.local

  endpoint: 10.0.3.5:80
  bucket: ne-hdfs
  accesskey: accesskey
  secretkey: secretkey

ne:
  version: 1.3.0-SNAPSHOT
  schema_version: 1.3.0
  sitename: nexr-gs
  licensekey: aWPl13uBrzYZ0QZg1X6T97lYRUOg6aN8yfrg+oFDoySseDbIBO7AX8ktWbw5rzVsqIPCbk35Hl7ycvTo1CKetKrNStZo/RXmZE7H2vYRj38MYKHTkd2LwX5SIEkyUU+pFoKiBkLNXK+IvbGASIPTHlORA05qgnjXwmlT48qM86M=

ne_admin_username: admin
ne_admin_password: admin

ne_ccs_install_timeout: 300
