---
- name: Copy File to /home/runner/etcdctl/
  copy: src="{{ item }}" dest=/home/runner/etcdctl/
  with_items:
    - rootca.crt
    - com.kt.cloud.datalake.crt
    - etcd-client.key

- name: Register NE-UI Traffik LoadBalancer Datalake-Mgmts
  shell: "etcdctl put traefik/tcp/services/{{ datalake_name }}/loadBalancer/servers/{{ item.key }}/address {{ item.value }}:30952 --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt' --key='/home/runner/etcdctl/etcd-client.key' --user 'root' --password '{{ etcd_root_password }}'"
  loop: "{{ datalake_mgmt_dict | dict2items }}" 

- name: Register NE-UI Traffik LoadBalancer rule HostSNI
  shell: "etcdctl put traefik/tcp/routers/{{ datalake_name }}/rule 'HostSNI(`{{ datalake_name }}.{{ ingress_vhost }}`)' --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"

- name: Register NE-UI Traffik LoadBalancer EntryPoints
  shell: "etcdctl put traefik/tcp/routers/{{ datalake_name }}/entryPoints/0 websecure --cacert='/home/runner/etcdctl/rootca.crt' --endpoints=datalake.cloud.kt.com:2379 --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"

- name: Register NE-UI Traffik LoadBalancer Service
  shell: "etcdctl put traefik/tcp/routers/{{ datalake_name }}/service {{ datalake_name }} --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"

- name: Register NE-UI Traffik LoadBalancer TLS
  shell: "etcdctl put traefik/tcp/routers/{{ datalake_name }}/tls/passthrough true --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"

- name: Register Pinpoint-UI Traffik LoadBalancer Datalake-Mgmts
  shell: "etcdctl put traefik/tcp/services/pinpoint-{{ datalake_name }}/loadBalancer/servers/{{ item.key }}/address {{ item.value }}:30952 --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt' --key='/home/runner/etcdctl/etcd-client.key' --user 'root' --password '{{ etcd_root_password }}'"
  loop: "{{ datalake_mgmt_dict | dict2items }}" 

- name: Register Pinpoint-UI Traffik LoadBalancer rule HostSNI
  shell: "etcdctl put traefik/tcp/routers/pinpoint-{{ datalake_name }}/rule 'HostSNI(`pinpoint-{{ datalake_name }}.{{ ingress_vhost }}`)' --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"

- name: Register Pinpoint-UI Traffik LoadBalancer EntryPoints
  shell: "etcdctl put traefik/tcp/routers/pinpoint-{{ datalake_name }}/entryPoints/0 websecure --cacert='/home/runner/etcdctl/rootca.crt' --endpoints=datalake.cloud.kt.com:2379 --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"


- name: Register Pinpoint-UI Traffik LoadBalancer Service
  shell: "etcdctl put traefik/tcp/routers/pinpoint-{{ datalake_name }}/service {{ datalake_name }} --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"


- name: Register Pinpoint-UI Traffik LoadBalancer TLS
  shell: "etcdctl put traefik/tcp/routers/pinpoint-{{ datalake_name }}/tls/passthrough true --endpoints=datalake.cloud.kt.com:2379 --cacert='/home/runner/etcdctl/rootca.crt' --cert='/home/runner/etcdctl/com.kt.cloud.datalake.crt'  --key='/home/runner/etcdctl/etcd-client.key'  --user 'root'  --password '{{ etcd_root_password }}'"
