---
- name: Check that the ldap directory file
  stat:
    path: "/home/centos/ne-ldap-templates"
  register: ldapdir

- name: Create Directory ne-ldap-templates
  file: path=/home/centos/ne-ldap-templates state=directory mode=0755 recurse=yes
  when: not ldapdir.stat.exists


- name: Copy File to ne-ldap-templates
  template: src=roles/ne-ldap/templates/{{ item }} dest=/home/centos/ne-ldap-templates
  with_items:
  - ldap_gateway_delete.json
  - ldap_gateway.json
  - ldap_istio_operator_delete.json
  - ldap_istio_operator.json
  when: not ldapdir.stat.exists

- name: Register for Istio Operators Index.
  shell:
    cmd: kubectl get istiooperators.install.istio.io istiocontrolplane -n istio-system -o json  | jq '.spec.components.ingressGateways[].k8s.service.ports | map(.name == "{{ datalake_name }}") | index(true)'
  register: istio_operator_index

- name: Change Parameter for Setting istio_operator 
  lineinfile:
    dest: '/home/centos/ne-ldap-templates/ldap_istio_operator.json'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    -  { regexp: '^\s{2,}"name":(.*)', line: '      "name": "{{ datalake_name }}",' }
    -  { regexp: '^\s{2,}"port":(.*)', line: '      "port": {{ ldap_inner_port }},' }    
    -  { regexp: '^\s{2,}"targetPort":(.*)', line: '      "targetPort": {{ ldap_inner_port }},' }    

- name: Patch Istiooperator With Ldap Information
  shell: kubectl patch istiooperators -n istio-system istiocontrolplane --type='json' --patch-file '/home/centos/ne-ldap-templates/ldap_istio_operator.json'
  when: istio_operator_index.stdout == "null"

- name: Get a istio_operator information
  community.kubernetes.k8s_info:
    api_version: install.istio.io/v1alpha1
    kind: IstioOperator
    namespace: istio-system
    name: istiocontrolplane
  register: info_istiocontrolplane

- name: Display istiocontrolplane
  debug:
    var: "info_istiocontrolplane.resources.0.spec.components.ingressGateways.0.k8s.service.ports"

- name: Register for Gateway Index.
  shell: kubectl get gateway datalake-gateway -n istio-system -o json  | jq '.spec.servers | map(.port.name=="{{ datalake_name }}") | index(true)'
  register: gateway_index

- name: Change Parameter for Setting Gateway 
  lineinfile:
    dest: '/home/centos/ne-ldap-templates/ldap_gateway.json'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    -  { regexp: '^\s{2,}(.*).datalake.cloud.kt.com(.*)', line: ' "{{ datalake_name }}.datalake.cloud.kt.com"' }
    -  { regexp: '^\s{2,}"name":(.*)', line: '        "name": "{{ datalake_name }}",'}       
    -  { regexp: '^\s{2,}"number":(.*)', line: '        "number": {{ ldap_inner_port }},'}    

- name: Patch Istiooperator With Ldap Information
  shell: kubectl patch gateways -n istio-system datalake-gateway --type='json' --patch-file '/home/centos/ne-ldap-templates/ldap_gateway.json'
  when: gateway_index.stdout == "null"


- name: Get a Gateway information
  community.kubernetes.k8s_info:
    api_version: networking.istio.io/v1beta1
    kind: Gateway
    namespace: istio-system
    name: datalake-gateway
  register: info_gateway

- name: Display istiocontrolplane-test
  debug:
    var: "info_gateway.resources.0.spec.servers"

