---
- name: Add NexR Enterprise chart repo
  community.kubernetes.helm_repository:
    name: "{{ chart_repo_name }}"
    state: present
    repo_url: "{{ chart_repo_url }}"

# - name: Templating values.yaml
#   template:
#     src: values.yaml
#     dest: /tmp/rook-ceph-values.yaml

- name: Create a k8s namespace for rook-ceph operator
  community.kubernetes.k8s:
    state: present
    definition:
      kind: Namespace
      api_version: v1
      metadata:
        name: "{{ rook_ceph.namespace }}"
        labels:
          istio-injection: disabled

- name: Deploy rook-ceph-block StorageClass chart
  community.kubernetes.helm:
    name: rook-ceph
    chart_ref: "{{ chart_repo_name }}/ne-rook-ceph"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ rook_ceph.namespace }}"
    wait: yes
    atomic: yes
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    # values:
    #   cephBlockPools:
    #   - name: "{{ cephBlockPool.name }}"
    #   csi:
    #     enableRbdDriver: true
    #     rbdStorageClasses:
    #     - name: rook-ceph-block-helm
    #       pool: "{{ cephBlockPool.name }}"
    #     enableCephfsDriver: false
    #   ceph:
    #     external:
    #       enable: "{{ ceph.external.enable }}"
    #       fsid: "{{ ceph.external.fsid }}"
    #       clientAdminKey: "{{ ceph.external.clientAdminKey }}"
    #       monKey: "{{ ceph.external.monKey }}"
    #       mons:
    #       {% for mon in ceph.external.mons %}
    #       - name: "{{ mon.name }}"
    #         addr: "{{ mon.addr }}"
    #       {% endfor %}
