---
- name: cephblockpool
  community.kubernetes.k8s:
    state: present
    definition:
      kind: CephBlockPool
      apiVersion: ceph.rook.io/v1
      metadata:
        name: robert-ceph-rbd-pool
        namespace: rook-ceph
     replicated:
       size: 3
       targetSizeRatio: 0

- name: check cephblockpool
  community.kubernetes.k8s_info: 
    name: cephblockpool
    kind: CephBlockPool
    api_version: ceph.rook.io/v1
  register: check_cephblockpool_result
  

- name: debug
  debug:
    var: check_cephblockpool_result
  when: check_cephblockpool_result is defined and check_cephblockpool_result.resources | length > 0

- name: storageclass
  community.kubernetes.k8s:
    state: present
    definition: 
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: robert-rook-ceph-block
      provisioner: rook-ceph.rbd.csi.ceph.com
      parameters:
        clusterID: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: roo-ceph
        imageFeatures: layering
        imageFormat: '2'
        pool: ceph-rbd-pool
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate

- name: Get k8s StorageClass object
  community.kubernetes.k8s_info:
    api_version: v1
    kind: StorageClass
    name: robert-rook-ceph-block
  register: check_storageclass_result

## create storageclass and cephpool for client
#

