---
- name: Add NexR Enterprise chart repo
  community.kubernetes.helm_repository:
    name: "{{ chart_repo_name }}"
    state: present
    repo_url: "{{ chart_repo_url }}"

- name: Create a k8s namespace for rook-ceph operator
  community.kubernetes.k8s:
    state: present
    definition:
      kind: Namespace
      api_version: v1
      metadata:
        name: "{{ rook_ceph.namespace }}"
        labels:
          istio-injection: disabled

- name: Deploy rook-ceph-block StorageClass chart
  community.kubernetes.helm:
    name: rook-ceph
    chart_ref: "{{ chart_repo_name }}/ne-rook-ceph"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ rook_ceph.namespace }}"
    wait: yes
    atomic: yes
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
