---
- name: Remove rook-ceph chart
  community.kubernetes.helm:
    name: rook-ceph
    release_namespace: "rook-ceph"
    state: absent
    wait: yes

- name: Remove a rook-ceph namespace for rook-ceph operator
  community.kubernetes.k8s:
    state: absent
    definition:
      kind: Namespace
      api_version: v1
      metadata:
        name: "rook-ceph"
    wait: yes
    wait_condition:
      status: "True"
      type: "Terminating"

- name: Get rook-ceph namespace finalizer
  shell: "{{ bin_dir }}/kubectl get --raw '/api/v1/namespaces/rook-ceph'"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  register: raw_namespace
  failed_when:
    - "raw_namespace.rc != 0"
    - "'NotFound' not in raw_namespace.stderr"

- name: Result rook-ceph namespace raw_namespace
  debug:
    var: raw_namespace

- name: Replace rook-ceph namespace finalizer
  shell: "echo {{ raw_namespace.stdout }} |sed 's/\"finalizers\":\\[\".*\"\\]/\"finalizers\":\\[\\]/' |{{ bin_dir }}/kubectl replace --raw '/api/v1/namespaces/rook-ceph/finalize' -f -"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
  when: raw_namespace.stdout != ""
