---
- name: Remove CephBlockPool with client
  community.kubernetes.k8s:
    state: absent
    namespace: "rook-ceph"
    definition:
      kind: CephBlockPool
      api_version: ceph.rook.io/v1
      metadata:
        name: "{{ client_name }}-ceph-rbd-pool"
    wait: yes
    wait_condition:
      status: "True"
      type: "Terminating"

- name: Remove StorageClass with client
  community.kubernetes.k8s:
    state: absent
    definition:
      kind: StorageClass
      api_version: storage.k8s.io/v1
      metadata:
        name: "{{ client_name }}-rook-ceph-block"
    wait: yes
    wait_condition:
      status: "True"
      type: "Terminating"
