---
- name: Remove rook-ceph chart
  community.kubernetes.helm:
    name: rook-ceph
    release_namespace: "rook-ceph"
    state: absent
    wait: yes

- name: Remove a rook-ceph namespace for rook-ceph operator
  community.kubernetes.k8s:
    state: absent
    definition:
      kind: Namespace
      api_version: v1
      metadata:
        name: "rook-ceph"
    wait: yes
    wait_condition:
      status: "True"
      type: "Terminating"

- name: Replace rook-ceph namespace finalizer
  shell: "{{ bin_dir }}/kubectl get --raw '/api/v1/namespaces/{{ k8s_namespace }}' | sed 's/\"finalizers\":\\[\".*\"\\]/\"finalizers\":\\[\\]/' |kubectl replace --raw '/api/v1/namespaces/{{ k8s_namespace }}/finalize' -f -"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/root') }}/.kube/config"
