---
- name: Remove pxc-database chart
  community.kubernetes.helm:
    name: rook-ceph
    release_namespace: "rook-ceph"
    state: absent
    wait: yes

- name: Remove a k8s namespace for rook-ceph operator
  community.kubernetes.k8s:
    state: absent
    definition:
      kind: Namespace
      api_version: v1
      metadata:
        name: "rook-ceph"
