kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services/proxy"]
    verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]

