chart_repo_name: ne-1.3.0

k8s_namespace: ne

ingress_vhost: nexr.kr

ne_version: 1.3.0
ne_schema_version: 1.3.0

ne_app:
  image_build_num: ""
  image_project: nexr-enterprise
  image_pullPolicy: IfNotPresent

ne_ui:
  image_build_num: ""
  image_project: nexr-enterprise
  image_pullPolicy: IfNotPresent

pinpoint:
  values:
    web:
      istio:
        hosts:
          - "apm.{{ ingress_vhost }}"

ccs:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/ccs-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true

cui:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_ui.image_project }}/constantine-ui"
      pullPolicy: "{{ ne_ui.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_ui.image_build_num if ne_ui.image_build_num is defined and ne_ui.image_build_num|length else '' }}"

cgw:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/cgw-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true
    istio:
      hosts:
        - "ne.{{ ingress_vhost }}"

openldap:
  values:
    istio:
      sidecar:
        enabled: false
      hosts:
        - "openldap.{{ ingress_vhost }}"

ranger_admin:
  values:
    istio:
      sidecar:
        enabled: false
      hosts:
        - "ranger.{{ ingress_vhost }}"

ranger_usersync:
  values:
    istio:
      sidecar:
        enabled: false

a3s:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/a3s-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true
        
prometheus:
  values:
    virtualServices:
      gateway: "nexr-gateway"
      namespace: "istio-system"
      # for each pod
      prometheusServer:
        hostname: "prometheus.{{ ingress_vhost }}"
        enabled: true
        portNumber: 80
        prefix: /
      alertManager:
        hostname: "alertmanager.{{ ingress_vhost }}"
        enabled: true
        portNumber: 80
        prefix: /

grafana:
  values:
    virtualServices:
      gateway: "nexr-gateway"
      namespace: "istio-system"
      grafana:
        hostname: "grafana.{{ ingress_vhost }}"
        enabled: true
        portNumber: 80
        prefix: /
