chart_repo_name: ne

k8s_namespace: ne

ingress_vhost: nexr.kr
ldap_port: 389

ne_version: 1.3.1
ne_schema_version: 1.3.1

ne_app:
  image_build_num: ""
  image_project: nexr-enterprise
  image_pullPolicy: IfNotPresent

ne_ui:
  image_build_num: ""
  image_project: nexr-enterprise
  image_pullPolicy: IfNotPresent

pinpoint:
  values:
    hbase:
      istio:
        gateways:
        - "{{ ingress_gateway }}"
      persistence:
        enabled: true
        storageClass: "{{ client_name }}-rook-ceph-block"
    web:
      istio:
        gateways:
        - "{{ ingress_gateway }}"
        hosts:
          - "apm.{{ ingress_vhost }}"

ccs:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/ccs-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true

cui:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_ui.image_project }}/constantine-ui"
      pullPolicy: "{{ ne_ui.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_ui.image_build_num if ne_ui.image_build_num is defined and ne_ui.image_build_num|length else '' }}"

cgw:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/cgw-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true
    istio:
      gateways:
      - "{{ ingress_gateway }}"
      hosts:
        - "{{ client_name }}.{{ ingress_vhost }}"

openldap:
  values:
    istio:
      sidecar:
        enabled: false
      gateways:
      - "{{ ingress_gateway }}"
      hosts:
        - "openldap.{{ ingress_vhost }}"
      tcp:
        matchPort: "{{ ldap_port }}"
    persistence:
      enabled: true
      storageClass: "{{ client_name }}-rook-ceph-block"

ranger_admin:
  values:
    istio:
      sidecar:
        enabled: false
      gateways:
      - "{{ ingress_gateway }}"
      hosts:
        - "ranger.{{ ingress_vhost }}"

ranger_usersync:
  values:
    istio:
      sidecar:
        enabled: false

a3s:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_app.image_project }}/a3s-server-web"
      pullPolicy: "{{ ne_app.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_app.image_build_num if ne_app.image_build_num is defined and ne_app.image_build_num|length else '' }}"
    ne:
      pinpoint:
        enabled: true