---
- name: Read access to Applications within a namespace
  shell: "{{ bin_dir }}/kubectl create -n {{ datalake_name }} rolebinding {{ datalake_name }}-kubeapps-view --clusterrole=kubeapps-applications-read --serviceaccount {{ datalake_name }}:{{ datalake_name }}"

- name: Write access to Applications within a namespace
  shell: "{{ bin_dir }}/kubectl create -n {{ datalake_name }} rolebinding {{ datalake_name }}-kubeapps-edit --clusterrole=edit --serviceaccount {{ datalake_name }}:{{ datalake_name }}"

- name: Read access to Service Instances and ClusterRole Bindings within a namespaces
  shell: "{{ bin_dir }}/kubectl create clusterrolebinding {{ datalake_name }}-kubeapps-service-catalog-browse --clusterrole=kubeapps-service-catalog-browse --serviceaccount {{ datalake_name }}:{{ datalake_name }}"
  ignore_errors: yes

- name: Read access to Service Instances and Role Bindings within a namespaces
  shell: "{{ bin_dir }}/kubectl create -n {{ datalake_name }} rolebinding {{ datalake_name }}-kubeapps-service-catalog-read --clusterrole=kubeapps-service-catalog-read --serviceaccount {{ datalake_name }}:{{ datalake_name }}"

- name: Write access to Service Instances and Bindings within a namespace
  shell: "{{ bin_dir }}/kubectl create -n {{ datalake_name }} rolebinding {{ datalake_name }}-kubeapps-service-catalog-write --clusterrole=kubeapps-service-catalog-write --serviceaccount {{ datalake_name }}:{{ datalake_name }}"

- name: Admin access to configure Service Brokers
  shell: "{{ bin_dir }}/kubectl create clusterrolebinding {{ datalake_name }}-kubeapps-service-catalog-admin --clusterrole=kubeapps-service-catalog-admin --serviceaccount {{ datalake_name }}:{{ datalake_name }}"
  ignore_errors: yes

- name: Read access to App Repositories
  shell: "{{ bin_dir }}/kubectl create -n kubeapps rolebinding {{ datalake_name }}-kubeapps-repositories-read --role=kubeapps-repositories-read --serviceaccount {{ datalake_name }}:{{ datalake_name }}"
  ignore_errors: yes

- name: Write access to App Repositories
  shell: "{{ bin_dir }}/kubectl create -n kubeapps rolebinding {{ datalake_name }}-kubeapps-repositories-write --role=kubeapps-repositories-write --serviceaccount {{ datalake_name }}:{{ datalake_name }}"
  ignore_errors: yes

- name: Create variable - k8s kubeapps token
  shell: "{{ bin_dir }}/kubectl describe -n {{ datalake_name }} secret $(kubectl get -n {{ datalake_name }} serviceaccount {{ datalake_name }} -o jsonpath='{.secrets[].name}') | grep -E '^token' | cut -f2 -d':' | tr -d ' '"
  environment:
    - KUBECONFIG: "{{ ansible_env.HOME | default('/home/centos') }}/.kube/config"
  register: kubeapps_token_result

- name: Set fact variable - k8s kubeapps token
  set_fact:
    cacheable: yes
    kubeapps_token: "{{ kubeapps_token_result.stdout }}"

- name: Set ststs variable - k8s kubeapps token
  set_stats:
    data:
      kubeapps_token: "{{ kubeapps_token }}"

- name: Change Kubeapps rest api info
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/orchestrators/1"
    method: PUT
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
    body:
      endpoint: "http://kubeapps.kubeapps.svc.{{ k8s_cluster_name }}:80"
      namespace: "{{ k8s_namespace }}"
      title: "Kubernetes"
      token: "{{ kubeapps_token }}"
  register: orchestrator_response

- name: Get k8s AppRepository object
  community.kubernetes.k8s_info:
    api_version: v1
    kind: AppRepository
    namespace: "{{ k8s_namespace }}"
    name: "{{ chart_repo_name }}"
  register: check_apprepository_result

- name: Debug When AppRepository is not installed
  debug:
    var: check_apprepository_result

- name: Generate ne apprepository when is not existed
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: kubeapps.com/v1alpha1
      kind: AppRepository
      metadata:
        name: "{{ chart_repo_name }}"
        namespace: "{{ k8s_namespace }}"
      spec:
        auth: {}
        resyncRequests: 0
        syncJobPodTemplate:
          metadata:
            creationTimestamp: null
          spec:
            containers: null
        type: helm
        url: "{{ chart_repo_url }}"
  when:
    - check_apprepository_result.status is undefined or
      check_apprepository_result.status is defined and check_apprepository_result.status.status == 'failed'
    - check_apprepository_result.resources is undefined or
      check_apprepository_result.resources | length <= 0
