---
- name: Deploy pinpoint chart
  community.kubernetes.helm:
    name: pinpoint
    chart_ref: "{{ chart_repo_name }}/pinpoint"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ k8s_namespace }}"
    wait: yes
    atomic: yes
    values: "{{  pinpoint['values'] | from_yaml }}"

- name: Check release pinpoint
  community.kubernetes.helm_info:
    name: pinpoint
    release_namespace: "{{ k8s_namespace }}"
  register: result
  until: "{{ result.status.status == 'deployed' }}"
  retries: 10
  delay: 10

- name: Deploy ccs chart
  community.kubernetes.helm:
    name: ccs
    chart_ref: "{{ chart_repo_name }}/ccs"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ k8s_namespace }}"
    wait: yes
    atomic: yes
    values: "{{  ccs['values'] | from_yaml }}"

- name: Deploy cui chart
  community.kubernetes.helm:
    name: cui
    chart_ref: "{{ chart_repo_name }}/cui"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ k8s_namespace }}"
    wait: yes
    atomic: yes
    values: "{{  cui['values'] | from_yaml }}"

- name: Deploy cgw chart
  community.kubernetes.helm:
    name: cgw
    chart_ref: "{{ chart_repo_name }}/cgw"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ k8s_namespace }}"
    atomic: yes
    values: "{{  cgw['values'] | from_yaml }}"

# - name: Deploy openldap chart
#   community.kubernetes.helm:
#     name: openldap
#     chart_ref: "{{ chart_repo_name }}/openldap"
#     chart_version: "{{ ne.version }}"
#     release_namespace: "{{ k8s_namespace }}"
#     atomic: yes
#     values:
#       istio:
#         sidecar:
#           enabled: false
#         hosts:
#           - "openldap.{{ ingress_vhost }}"

# - name: Deploy ranger-admin chart
#   community.kubernetes.helm:
#     name: ranger-admin
#     chart_ref: "{{ chart_repo_name }}/ranger-admin"
#     chart_version: "{{ ne.version }}"
#     release_namespace: "{{ k8s_namespace }}"
#     wait: yes
#     atomic: yes
#     values:
#       istio:
#         sidecar:
#           enabled: false
#         hosts:
#           - "ranger.{{ ingress_vhost }}"

# - name: Deploy ranger-usersync chart
#   community.kubernetes.helm:
#     name: ranger-usersync
#     chart_ref: "{{ chart_repo_name }}/ranger-usersync"
#     chart_version: "{{ ne.version }}"
#     release_namespace: "{{ k8s_namespace }}"
#     atomic: yes
#     values:
#       istio:
#         sidecar:
#           enabled: false

- name: Deploy a3s chart
  community.kubernetes.helm:
    name: a3s
    chart_ref: "{{ chart_repo_name }}/a3s"
    chart_version: "{{ ne.version }}"
    release_namespace: "{{ k8s_namespace }}"
    wait: yes
    atomic: yes
    values: "{{  a3s['values'] | from_yaml }}"

