bin_dir: /usr/local/bin

chart_repo_name: ne-1.3.0-snapshot

k8s_namespace: ne

ingress_vhost: nexr.kr
pxc_port: 33306

s3:
  endpoint: 10.0.3.5:80
  bucket: dl-official
  accesskey: 5M4SROOODT1DCSAOM8IA
  secretkey: BMaqeU1XjbkaKW99F1ucMeEVFRIYHHMPsOf7RvZs
  backup_bucket: bk-official

ne:
  version: 1.3.0-SNAPSHOT
  schema_version: 1.3.0

user_subdomain: nexrtest
