bin_dir: /usr/local/bin

chart_repo_name: ne-1.3.1

k8s_namespace: "ne"

ingress_vhost: nexr.kr
pxc_port: 33306
ldap_port: 389

s3:
  endpoint: 10.0.3.5:80
  bucket: dl-official
  accesskey: 5M4SROOODT1DCSAOM8IA
  secretkey: BMaqeU1XjbkaKW99F1ucMeEVFRIYHHMPsOf7RvZs
  backup_bucket: bk-official

user_subdomain: nexrtest

ne_version: "1.3.1"
ne_schema_version: "1.3.1"

ne_context:
  image_build_num: ""
  image_project: nexr-enterprise
  image_pullPolicy: IfNotPresent

pmm_server:
  values:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "{{ client_name }}-rook-ceph-block"
    resources:
      requests:
        memory: 4Gi
        cpu: 1
    virtualServices:
      gateway: "{{ ingress_gateway_full_fqdn }}"
      namespace: "{{ k8s_namespace }}"
      pmm:
        hostname: "pmm.{{ ingress_gateway_full_fqdn }}"

pxc_database:
  values:
    pxc:
      persistence:
        enabled: true
        storageClass: "{{ client_name }}-rook-ceph-block"
    proxysql:
      size: 2
      persistence:
        enabled: true
        storageClass: "{{ client_name }}-rook-ceph-block"
    virtualServices:
      gateway: "{{ ingress_gateway_full_fqdn }}"
      namespace: "{{ k8s_namespace }}"
      pxcProxy:
        hostname: "mysql.{{ ingress_gateway_full_fqdn }}"
        matchPortNumber: "{{ pxc_port }}"
    backup:
      storages:
        persistentVolumeClaim:
          storageClassName: "{{ client_name }}-rook-ceph-block"
ne_init:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_context.image_project }}/ne-init"
      pullPolicy: "{{ ne_context.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_context.image_build_num if ne_context.image_build_num is defined and ne_context.image_build_num|length else '' }}"
    envOverrides:
      S3_ENDPOINT: "{{ s3.endpoint }}"
      S3_BUCKET: "{{ s3.bucket }}"
      S3_ACCESSKEY: "{{ s3.accesskey }}"
      S3_SECRETKEY: "{{ s3.secretkey }}"
      MYSQL_SERVER: pxc-database-proxysql
      MYSQL_PORT: 3306
      NEXUS_HOST: nexus
      HOST_REPO_NAME: nexr-host
      GROUP_REPO_NAME: nexr-maven
      NE_SCHEMA_VERSION: "{{ ne_schema_version }}"
      NE_NAMESPACE: "{{ k8s_namespace }}"
      CHART_REPO_NAME: "{{ chart_repo_name }}"
      DATALAKE_USER_HOST: "https://{{ client_name }}.datalake.cloud.kt.com"
      ISTIO_SIDECAR_ENABLE: "false"

nexus:
  values:
    image:
      pullPolicy: "{{ ne_context.image_pullPolicy }}"

ne_depend:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_context.image_project }}/ne-depend"
      pullPolicy: "{{ ne_context.image_pullPolicy }}"
      tag: "{{ ne_version }}{{ '-' ~ ne_context.image_build_num if ne_context.image_build_num is defined and ne_context.image_build_num|length else '' }}"
    resources:
      requests:
        memory: 5Gi
        cpu: 2000m
