bin_dir: /usr/local/bin

chart_repo_name: ne-1.2.0-aidx

k8s_namespace: ne

ingress_vhost: nexr.kr
pxc_port: 33306

s3:
  endpoint: 10.0.3.5:80
  bucket: dl-username
  accesskey: 5M4SROOODT1DCSAOM8IA
  secretkey: BMaqeU1XjbkaKW99F1ucMeEVFRIYHHMPsOf7RvZs
  backup_bucket: bk-username

user_subdomain: nexrtest

ne:
  version: 1.2.0
  schema_version: 1.2.0

ne_context:
  image_build_num: ""
  image_project: nexr-enterprise
  imgae_pullPolicy: Always

pmm_server:
  values:
    persistence:
      size: 100Gi
    resources:
      requests:
        memory: 4Gi
        cpu: 1
    virtualServices:
      pmm:
        hostname: "pmm.{{ ingress_vhost }}"

pxc_database:
  values:
    proxysql:
      size: 2
    virtualServices:
      pxcProxy:
        hostname: "mysql.{{ ingress_vhost }}"
        matchPortNumber: "{{ pxc_port }}"

ne_init:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_context.image_project }}/ne-init"
      pullPolicy: "{{ ne_context.imgae_pullPolicy }}"
      tag: "{{ ne.version }}{{ '-' ~ ne_context.image_build_num if ne_context.image_build_num is defined and ne_context.image_build_num|length else '' }}"
    envOverrides:
      S3_ENDPOINT: "{{ s3.endpoint }}"
      S3_BUCKET: "{{ s3.bucket }}"
      S3_ACCESSKEY: "{{ s3.accesskey }}"
      S3_SECRETKEY: "{{ s3.secretkey }}"
      MYSQL_SERVER: pxc-database-proxysql
      MYSQL_PORT: 3306
      NEXUS_HOST: nexus
      HOST_REPO_NAME: nexr-host
      GROUP_REPO_NAME: nexr-maven
      NE_VERSION: "{{ ne.schema_version }}"
      NE_NAMESPACE: "{{ k8s_namespace }}"
      CHART_REPO_NAME: "{{ chart_repo_name }}"

nexus:
  values:
    image:
      pullPolicy: "{{ ne_context.imgae_pullPolicy }}"

ne_depend:
  values:
    image:
      repository: "harbor.nexr.kr/{{ ne_context.image_project }}/ne-depend"
      pullPolicy: "{{ ne_context.imgae_pullPolicy }}"
      tag: "{{ ne.version }}{{ '-' ~ ne_context.image_build_num if ne_context.image_build_num is defined and ne_context.image_build_num|length else '' }}"
    resources:
      requests:
        memory: 5Gi
        cpu: 2000m
