---
- name: Regist NexR Enterprise license
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/ccs:8180/proxy/licenses/constantine"
    method: POST
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
    body:
      licenseKey: "{{ ne.licensekey }}"
      siteName: "{{ ne.sitename }}"

- name: Login NexR Enterprise
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/a3s:8189/proxy/auth/login"
    method: POST
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
    body:
      userId: "{{ ne_admin_username }}"
      userPassword: "{{ ne_admin_password }}"
  register: login_response

- name: Set ststs variable - NexR Enterprise accesstoken
  set_stats:
    data:
      ne_accesstoken: "{{ login_response.json.body.accessToken }}"
      ne_refreshtoken: "{{ login_response.json.body.refreshToken }}"

- name: Set fact variable - NexR Enterprise accesstoken
  set_fact:
    cacheable: yes
    ne_accesstoken: "{{ login_response.json.body.accessToken }}"
    ne_refreshtoken: "{{ login_response.json.body.refreshToken }}"

- name: Add Portal User
  uri:
    url: "{{ k8s_api_server }}/api/v1/namespaces/{{ k8s_namespace }}/services/a3s:8189/proxy/users"
    method: POST
    body_format: json
    follow_redirects: all
    validate_certs: no
    timeout: "{{ ne_ccs_install_timeout }}"
    headers:
      Authorization: "Bearer {{ k8s_api_token }}"
      x-constantine-token: "{{ ne_accesstoken }}"
      content-type: application/json;charset=UTF-8
    body:
      userId: "{{ user_id }}"
      userName: "{{ user_id.split('@')[0] | replace('.','-') | lower }}"
      password: "{{ user_id.split('@')[0] | replace('.','-') | lower }}"
      email: "{{ user_id }}"
      channelReceiveYn: false
      emailReceiveYn: true
      useYn: true
      roles:
        - id: 1
          name: "ADMINISTRATOR"
  register: new_user
