kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
